### PR TITLE
Added fix to test script. Added requirements to pipfile.

### PR DESCRIPTION
**Pull request by hstewart93**
- Updated requirements
- Added hotfix
- `oil_predictor_tests.py` reformatted by black autoformatter on commit

### CODE REVIEW

**Review by thomas-spriggs-codes — COMMENTED** [review]
Am i right in saying the only non-formatting change is dates[] --> dates[0]?

**Comment by thomas-spriggs-codes** [comment]
other than the changes to pip file

**Comment by hstewart93** [comment]
> other than the changes to pip file

yeah that's the only change

**Comment by thomas-spriggs-codes** [comment]
then to quote simon cowell, 'its a yes from me'

**Review by thomas-spriggs-codes — APPROVED** [review]

**Pull request merged**
