### PR TITLE
Configure development tools

### PR DESCRIPTION
**Pull request by hstewart93**
- Add pipenv for package management
- Add black and flake8
- Add pre-commit to run black and flake8 on `git commit`
- Add installation instructions to README

### CODE REVIEW

**Review by thomas-spriggs-codes — COMMENTED** [review]
nice1

**Review by mrknorman — APPROVED** [review]
Looks good to me, although there's a bunch of stuff I've never used in here so I may need your assistance at some point with some things. Glad we have you on the team to organize things though. @hstewart93

**Comment by TonichaC** [comment]
Ive done what the read me said to do, but Ive never used git or these environments before

**Comment by hstewart93** [comment]
@TheEmporerNorman @TonichaC - They're all very simple tools once you get used them, I'll try to write up a little crib sheet of how to get these processes working for you in a way that hopefully makes the work more streamlined and efficient - if anything ever seems wierd or confusing just let me know and I'll try to explain best I can - and also if you have any issues installing stuff according to the readme instructions let me know and I can update it :)

**Comment by TonichaC** [comment]
Thank you a cheat sheet would be great! I've installed everything and think its all set up as intended

**Comment by hstewart93** [comment]
> Thank you a cheat sheet would be great! I've installed everything and think its all set up as intended

I'll merge in this branch and then add one to the repo in a separate pr, so it's easily accessible

**Pull request merged**
